version: '3.8'
services:
  app:
    build: ./
    container_name: app
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./src:/usr/app/src
      - logData:/usr/app/logs
    networks:
      - app-network
    depends_on:
      - db
  db:
    build: ./db/
    container_name: db
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    volumes:
      - dbData:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  logData:
  dbData:
